PT-13108 - Fix general setting landing page with default value
shopware5/SwagPaymentPayPalUnified pull request #27
Opened 2023-06-19 12:20 UTC by swDennis

2023-06-20 08:37 UTC, mitelg requested changes
- test is missing
- plugin.xml entry is missing

2023-06-21 06:17 UTC, swDennis commented
> * test is missing
> * plugin.xml entry is missing

Done

2023-06-21 08:21 UTC, mitelg commented on plugin.xml
> +            PT-13108 - Setzt Standard-Landingpage, wenn keine ausgewählt wurde;
```suggestion
            PT-13108 - Nutzt Standard-Landingpage, wenn die Einstellung nicht korrekt gesetzt wurde;
```

2023-06-21 09:27 UTC, mitelg approved these changes

2023-06-27 08:40 UTC, ennasus4sun approved these changes

2023-06-27 08:40 UTC, merged