PT-13115 - Add handling for cards without authentication system. Show…
shopware5/SwagPaymentPayPalUnified pull request #30
Opened 2023-06-22 09:29 UTC by swDennis

… message to the customer.

2023-06-30 09:08 UTC, rathmerdominik approved these changes

2023-06-30 12:43 UTC, mitelg requested changes

2023-06-30 12:43 UTC, mitelg commented on Resources/services/components.xml
> +            <argument type="service" id="paypal_unified.settings_service"/>
the ThreeDSecureResultChecker does not have any dependency at all :thinking:

2023-07-04 06:58 UTC, mitelg approved these changes

2023-07-04 06:59 UTC, merged